import type { CountryConfig } from "@/lib/countries/types";

/** Gabon — Mobile Money local (Airtel / Moov). */
export const GA: CountryConfig = {
  code: "GA",
  name: "Gabon",
  currency: "XAF",
  cities: [
    "Libreville",
    "Port-Gentil",
    "Franceville",
    "Oyem",
    "Moanda",
    "Mouila",
    "Lambaréné",
    "Tchibanga",
    "Makokou",
    "Koulamoutou",
    "Bitam",
    "Owendo",
    "Ntoum",
    "Akanda",
    "Gamba",
    "Lastoursville",
    "Mayumba",
    "Ndendé",
    "Okondja",
    "Mitzic",
    "Ndjolé",
    "Fougamou",
    "Booué",
    "Cocobeach",
  ],
  services: [
    "colis",
    "hebergement",
    "maison",
    "artisanat",
    "beaute",
    "famille",
    "evenements",
    "transport",
    "transitaire",
    "formation",
    "consultation",
    "association",
    "service_public",
    "autre",
  ],
  payments: ["airtel_money", "moov_money", "mobile_money", "bank"],
  transportModes: ["AIR", "ROAD", "SEA"],
  communityWhatsApp: "RFacto Gabon",
  features: { kycRequired: true, escrow: true },
};
