import { COUNTRIES } from "@/lib/corridors";

/** ISO currency metadata (rates approx. vs CAD for display/future FX). */
export const CURRENCIES = [
  { code: "CAD", name: "Dollar canadien", symbol: "CA$", exchangeRate: 1 },
  { code: "USD", name: "Dollar américain", symbol: "US$", exchangeRate: 0.74 },
  { code: "EUR", name: "Euro", symbol: "€", exchangeRate: 0.68 },
  { code: "GBP", name: "Livre sterling", symbol: "£", exchangeRate: 0.58 },
  { code: "XAF", name: "Franc CFA (BEAC)", symbol: "FCFA", exchangeRate: 450 },
  { code: "XOF", name: "Franc CFA (BCEAO)", symbol: "CFA", exchangeRate: 450 },
  { code: "MAD", name: "Dirham marocain", symbol: "MAD", exchangeRate: 7.3 },
  { code: "DZD", name: "Dinar algérien", symbol: "DA", exchangeRate: 98 },
  { code: "TND", name: "Dinar tunisien", symbol: "DT", exchangeRate: 2.3 },
  { code: "EGP", name: "Livre égyptienne", symbol: "E£", exchangeRate: 36 },
  { code: "NGN", name: "Naira", symbol: "₦", exchangeRate: 1200 },
  { code: "GHS", name: "Cedi ghanéen", symbol: "GH₵", exchangeRate: 11 },
  { code: "KES", name: "Shilling kenyan", symbol: "KSh", exchangeRate: 95 },
  { code: "ZAR", name: "Rand sud-africain", symbol: "R", exchangeRate: 13.5 },
  { code: "CHF", name: "Franc suisse", symbol: "CHF", exchangeRate: 0.65 },
  { code: "JPY", name: "Yen", symbol: "¥", exchangeRate: 110 },
  { code: "CNY", name: "Yuan", symbol: "¥", exchangeRate: 5.3 },
  { code: "AED", name: "Dirham des EAU", symbol: "AED", exchangeRate: 2.7 },
  { code: "INR", name: "Roupie indienne", symbol: "₹", exchangeRate: 62 },
  { code: "BRL", name: "Real brésilien", symbol: "R$", exchangeRate: 3.7 },
  { code: "AUD", name: "Dollar australien", symbol: "A$", exchangeRate: 1.1 },
] as const;

export const LANGUAGES = [
  { code: "fr", name: "Français" },
  { code: "en", name: "English" },
] as const;

const CONTINENT_BY_CODE: Record<string, string> = {
  CA: "Amérique du Nord",
  US: "Amérique du Nord",
  MX: "Amérique du Nord",
  HT: "Caraïbes",
  DO: "Caraïbes",
  CU: "Caraïbes",
  JM: "Caraïbes",
  GP: "Caraïbes",
  MQ: "Caraïbes",
  GF: "Amérique du Sud",
  BR: "Amérique du Sud",
  AR: "Amérique du Sud",
  CL: "Amérique du Sud",
  CO: "Amérique du Sud",
  PE: "Amérique du Sud",
  VE: "Amérique du Sud",
  EC: "Amérique du Sud",
  SN: "Afrique",
  CI: "Afrique",
  ML: "Afrique",
  BF: "Afrique",
  GN: "Afrique",
  BJ: "Afrique",
  TG: "Afrique",
  NE: "Afrique",
  GH: "Afrique",
  NG: "Afrique",
  MR: "Afrique",
  CM: "Afrique",
  GA: "Afrique",
  CG: "Afrique",
  CD: "Afrique",
  CF: "Afrique",
  TD: "Afrique",
  GQ: "Afrique",
  KE: "Afrique",
  TZ: "Afrique",
  UG: "Afrique",
  ET: "Afrique",
  RW: "Afrique",
  BI: "Afrique",
  MG: "Afrique",
  MU: "Afrique",
  RE: "Afrique",
  ZA: "Afrique",
  MA: "Afrique",
  DZ: "Afrique",
  TN: "Afrique",
  EG: "Afrique",
  FR: "Europe",
  BE: "Europe",
  CH: "Europe",
  LU: "Europe",
  GB: "Europe",
  DE: "Europe",
  ES: "Europe",
  IT: "Europe",
  PT: "Europe",
  NL: "Europe",
  IE: "Europe",
  SE: "Europe",
  NO: "Europe",
  DK: "Europe",
  PL: "Europe",
  RO: "Europe",
  TR: "Europe",
  AE: "Moyen-Orient",
  SA: "Moyen-Orient",
  QA: "Moyen-Orient",
  IL: "Moyen-Orient",
  IN: "Asie",
  PK: "Asie",
  BD: "Asie",
  CN: "Asie",
  HK: "Asie",
  JP: "Asie",
  KR: "Asie",
  SG: "Asie",
  MY: "Asie",
  TH: "Asie",
  VN: "Asie",
  PH: "Asie",
  ID: "Asie",
  AU: "Océanie",
  NZ: "Océanie",
};

const CURRENCY_BY_CODE: Record<string, string> = {
  CA: "CAD",
  US: "USD",
  MX: "USD",
  FR: "EUR",
  BE: "EUR",
  DE: "EUR",
  ES: "EUR",
  IT: "EUR",
  PT: "EUR",
  NL: "EUR",
  IE: "EUR",
  LU: "EUR",
  GP: "EUR",
  MQ: "EUR",
  GF: "EUR",
  RE: "EUR",
  CH: "CHF",
  GB: "GBP",
  GA: "XAF",
  CM: "XAF",
  CG: "XAF",
  TD: "XAF",
  CF: "XAF",
  GQ: "XAF",
  SN: "XOF",
  CI: "XOF",
  ML: "XOF",
  BF: "XOF",
  BJ: "XOF",
  TG: "XOF",
  NE: "XOF",
  GN: "XOF",
  MA: "MAD",
  DZ: "DZD",
  TN: "TND",
  EG: "EGP",
  NG: "NGN",
  GH: "GHS",
  KE: "KES",
  ZA: "ZAR",
  AE: "AED",
  SA: "USD",
  QA: "USD",
  IN: "INR",
  CN: "CNY",
  HK: "USD",
  JP: "JPY",
  KR: "USD",
  SG: "USD",
  AU: "AUD",
  NZ: "USD",
  BR: "BRL",
  CD: "USD",
  HT: "USD",
};

const FLAG_BY_CODE: Record<string, string> = {
  CA: "🇨🇦",
  US: "🇺🇸",
  FR: "🇫🇷",
  BE: "🇧🇪",
  DE: "🇩🇪",
  GB: "🇬🇧",
  GA: "🇬🇦",
  CM: "🇨🇲",
  CI: "🇨🇮",
  SN: "🇸🇳",
  CD: "🇨🇩",
  CG: "🇨🇬",
  MA: "🇲🇦",
  TN: "🇹🇳",
  NG: "🇳🇬",
  KE: "🇰🇪",
  ZA: "🇿🇦",
  CN: "🇨🇳",
  AE: "🇦🇪",
  BR: "🇧🇷",
  IN: "🇮🇳",
  JP: "🇯🇵",
};

export function getContinent(code: string) {
  return CONTINENT_BY_CODE[code] ?? "Autre";
}

export function getDefaultCurrency(code: string) {
  return CURRENCY_BY_CODE[code] ?? "USD";
}

export function getFlag(code: string) {
  return FLAG_BY_CODE[code] ?? "🌍";
}

export function buildGeoSeed() {
  const countries = COUNTRIES.map((c) => ({
    code: c.code,
    name: c.name,
    continent: getContinent(c.code),
    flagEmoji: getFlag(c.code),
    currencyCode: getDefaultCurrency(c.code),
    cities: c.cities,
  }));
  return { currencies: CURRENCIES, languages: LANGUAGES, countries };
}
